create extension if not exists "vector" with schema "public";


  create table "public"."transcript_chunks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "transcript_id" bigint,
    "chunk_text" text,
    "embedding" public.vector
      );


alter table "public"."transcript_chunks" enable row level security;


  create table "public"."transcripts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "url" text,
    "transcript" text
      );


alter table "public"."transcripts" enable row level security;

CREATE UNIQUE INDEX transcript_chunks_pkey ON public.transcript_chunks USING btree (id);

CREATE UNIQUE INDEX transcripts_pkey ON public.transcripts USING btree (id);

alter table "public"."transcript_chunks" add constraint "transcript_chunks_pkey" PRIMARY KEY using index "transcript_chunks_pkey";

alter table "public"."transcripts" add constraint "transcripts_pkey" PRIMARY KEY using index "transcripts_pkey";

alter table "public"."transcript_chunks" add constraint "transcript_chunks_transcript_id_fkey" FOREIGN KEY (transcript_id) REFERENCES public.transcripts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."transcript_chunks" validate constraint "transcript_chunks_transcript_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.match_transcript_chunk(query_embedding public.vector, match_count integer DEFAULT 5, match_threshold double precision DEFAULT 0)
 RETURNS TABLE(id bigint, transcript_id text, chunk_text text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    t.id,
    t.transcript_id,
    t.chunk_text,
    1 - (t.embedding <=> query_embedding) as similarity
  from transcript_chunks t
  where 1 - (t.embedding <=> query_embedding) > match_threshold
  order by t.embedding <=> query_embedding
  limit match_count;
$function$
;

grant delete on table "public"."transcript_chunks" to "anon";

grant insert on table "public"."transcript_chunks" to "anon";

grant references on table "public"."transcript_chunks" to "anon";

grant select on table "public"."transcript_chunks" to "anon";

grant trigger on table "public"."transcript_chunks" to "anon";

grant truncate on table "public"."transcript_chunks" to "anon";

grant update on table "public"."transcript_chunks" to "anon";

grant delete on table "public"."transcript_chunks" to "authenticated";

grant insert on table "public"."transcript_chunks" to "authenticated";

grant references on table "public"."transcript_chunks" to "authenticated";

grant select on table "public"."transcript_chunks" to "authenticated";

grant trigger on table "public"."transcript_chunks" to "authenticated";

grant truncate on table "public"."transcript_chunks" to "authenticated";

grant update on table "public"."transcript_chunks" to "authenticated";

grant delete on table "public"."transcript_chunks" to "postgres";

grant insert on table "public"."transcript_chunks" to "postgres";

grant references on table "public"."transcript_chunks" to "postgres";

grant select on table "public"."transcript_chunks" to "postgres";

grant trigger on table "public"."transcript_chunks" to "postgres";

grant truncate on table "public"."transcript_chunks" to "postgres";

grant update on table "public"."transcript_chunks" to "postgres";

grant delete on table "public"."transcript_chunks" to "service_role";

grant insert on table "public"."transcript_chunks" to "service_role";

grant references on table "public"."transcript_chunks" to "service_role";

grant select on table "public"."transcript_chunks" to "service_role";

grant trigger on table "public"."transcript_chunks" to "service_role";

grant truncate on table "public"."transcript_chunks" to "service_role";

grant update on table "public"."transcript_chunks" to "service_role";

grant delete on table "public"."transcripts" to "anon";

grant insert on table "public"."transcripts" to "anon";

grant references on table "public"."transcripts" to "anon";

grant select on table "public"."transcripts" to "anon";

grant trigger on table "public"."transcripts" to "anon";

grant truncate on table "public"."transcripts" to "anon";

grant update on table "public"."transcripts" to "anon";

grant delete on table "public"."transcripts" to "authenticated";

grant insert on table "public"."transcripts" to "authenticated";

grant references on table "public"."transcripts" to "authenticated";

grant select on table "public"."transcripts" to "authenticated";

grant trigger on table "public"."transcripts" to "authenticated";

grant truncate on table "public"."transcripts" to "authenticated";

grant update on table "public"."transcripts" to "authenticated";

grant delete on table "public"."transcripts" to "postgres";

grant insert on table "public"."transcripts" to "postgres";

grant references on table "public"."transcripts" to "postgres";

grant select on table "public"."transcripts" to "postgres";

grant trigger on table "public"."transcripts" to "postgres";

grant truncate on table "public"."transcripts" to "postgres";

grant update on table "public"."transcripts" to "postgres";

grant delete on table "public"."transcripts" to "service_role";

grant insert on table "public"."transcripts" to "service_role";

grant references on table "public"."transcripts" to "service_role";

grant select on table "public"."transcripts" to "service_role";

grant trigger on table "public"."transcripts" to "service_role";

grant truncate on table "public"."transcripts" to "service_role";

grant update on table "public"."transcripts" to "service_role";


  create policy "anyone can insert"
  on "public"."transcript_chunks"
  as permissive
  for insert
  to public
with check (true);



  create policy "anyone can select"
  on "public"."transcript_chunks"
  as permissive
  for select
  to public
using (true);



  create policy "anyone can insert"
  on "public"."transcripts"
  as permissive
  for insert
  to public
with check (true);



  create policy "anyone can select"
  on "public"."transcripts"
  as permissive
  for select
  to public
using (true);



